module.exports = {
    SERVER_ERROR: 'SERVER_ERROR',
    USER_NOT_EXIST: 'USER_NOT_EXIST',
    SNIPPET_NOT_EXIST: 'SNIPPET_NOT_EXIST',
    SNIPPET_TYPE_NOT_EXIST: 'SNIPPET_TYPE_NOT_EXIST',
    PERMISSION_NOT_ALLOWED: 'PERMISSION_NOT_ALLOWED'
};